config/routes.rb
FinalExam1::Application.routes.draw do
  devise_for :users
  root 'welcome#index'
  resources :auctions do
    resources :bids, only: [:create, :destroy]
  end
  resources :auctions, only: [] do
    patch :publish, :reserve, on: :member
  end
  resources :profiles, only: [:index, :show]

end

app/models/auction.rb
class Auction < ActiveRecord::Base
  belongs_to :user
  has_many :bids, dependent: :destroy 
  validates_presence_of :title
  validates :reserve_price, presence: true, numericality: {greater_than_or_equal_to: 1}
  default_scope order("created_at DESC")
  scope :published, -> { where(state: :published) }
  after_initialize :set_default_current_price 
  
  state_machine :state, initial: :draft do
    event :publish do
      transition draft: :published
    end
    event :reserve do
      transition published: :reserve_met
    end

  end
  private
    def set_default_current_price
      self.current_price ||= 0
    end
  
  #validate :add_to_bids
  # def add_to_bids
  #   if self.bids.price < self.current_price
  #end
end

app/models/bid.rb
class Bid < ActiveRecord::Base
  
  belongs_to :user
  belongs_to :auction
  validates :price, presence: true, numericality: {greater_than_or_equal_to: 0} 
  default_scope order("created_at DESC")
  #delegate :user, to: :auction
  # def user
  #   auction.user
  # end
  


  #validates_numericality_of :price, :greater_than => Proc.new { |r| r.auction.current_price } 
  #after_initialize :set_default_current_price 
  #after_save :set_current_price
   # def set_default_current_price
  #   current_price ||= 0
  #end
  #has_one :current_price
  #after_initialize :set_default_current_price 
  
 # after_save :set_price
  #validates :price, :numericality => { :greater_than => lambda { |x| x.current_price } }
  #validate :my_attr_is_within_range
  #validates_uniqueness_of :price, :scope => [:current_price]

  #def my_attr_is_within_range
   # if price < current_price
    #  errors.add(:price, "can't less than current")
   # end
  #end

 # def set_price
  #  self.price = self.auction.price
 # end
 # def set_default_current_price
  #    self.current_price ||= 0
 # end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :auctions
  has_many :bids
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_devise_params, if: :devise_controller?

  def configure_devise_params
    devise_parameter_sanitizer.for(:sign_up) << 
                                    [:user_name]
    devise_parameter_sanitizer.for(:account_update) << 
                                    [:user_name]
  end
end

app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController
    
  before_action :authenticate_user!, except: [:show]
  before_action :find_auction, only: [:edit, :update, :destroy]
  
  def index    
    @auctions = current_user.auctions.paginate(:page => params[:page], :per_page => 5).order('created_at DESC')
  end
  
  def new   
    @auction = Auction.new
  end

  def create    
    @auction = current_user.auctions.new(auction_params)
    if @auction.save
      redirect_to auctions_path 
      flash[:success] = "Your auction is ready to be published"
    else
      flash.now[:alert] = "Please correct the form"
      render :new
    end
  end

  def show
    @auction = Auction.find(params[:id])
    @bid =  Bid.new
    @bids = @auction.bids.paginate(:page => params[:page], :per_page => 5) 
    #@price = @auction.bids.last || Bid.new
  end

  def edit
    # renders the edit page for the question passed
    #redirect_to root_path unless can? :edit, @question
  end

  def update
    if @auction.update_attributes(auction_params) 
      redirect_to @auction, notice: "Updated successfully"
    else
      flash.now[:alert] = "Update failed"
      render :edit
    end
  end
  
  def destroy
    if current_user == @auction.user && @auction.destroy 
      redirect_to auctions_path, alert: "Auction deleted!"
    else
      flash.now[:alert] = "Delete failed"
      render @auction  
    end
  end
  
  def publish 
    @auction = Auction.find(params[:id])
    if @auction.publish
      redirect_to root_path, success: "Your auction is now published for all the world to see!"
    else
      redirect_to auctions_path, alert: "Your auction cannot be published!"
    end
  
  end
  def reserve
    @auction = Auction.find(params[:id])
    if @auction.reserve
      redirect_to @auction
      flash[:success] = "You have reserved this item!" 
    else
      redirect_to @auction, alert:  "You already reserved this item!"
    end
  end
  
  #def reserve
   # @auction = Auction.find(params[:id])
   # @bid = @auction.bids.find(params[:bid_id])
    #if @bid.price == @auction.reserve_price || @bid.price > @auction.reserve_price
     #if @auction.reserve
      #redirect_to @auction, notice: "Campaign published successfully."
      #else
      #render :text => "cant reserve due to error"

      #redirect_to campaigns_path, alter: "Campaign publishing failed: #{@campaign.errors.full_messages}"
    #end
    #end
  #end

   private
    def auction_params
      auction_params = params.require(:auction).permit([:title, :details, :ends_on, :reserve_price, :current_price])
    end
    def find_auction
     # @auction = Auction.find(params[:id] || params[:auction_id])
      @auction = current_user.auctions.find_by_id(params[:id])
      redirect_to root_path, alert: "Access denied, foo" unless @auction
    end
end

app/controllers/bids_controller.rb
class BidsController < ApplicationController

  before_action :authenticate_user!
  def create
    @auction = Auction.find(params[:auction_id]) 
    @bid = @auction.bids.new(bids_params)
    @bid.user = current_user
    alert1 = "alert('You cant bid on you own auction, fool');"
    alert2 = "alert('Please enter a valid number that is higher than the current bid!');"  
    respond_to do |format| 
      if valid_bid     
        @auction.update_attributes(current_price: @bid.price + 1)
        format.html { redirect_to @auction, notice: "Bid created happilly!" }
        format.js { render } 
      else
        if current_user == @auction.user 
          format.html { redirect_to @auction, alert: alert1 }
          format.js { render js: alert1 } 
        else
          format.html { render "auctions/show", alert: alert2  }
          format.js { render js: alert2 }
        end
      end
    end
  end

  def destroy
    @auction = Auction.find(params[:auction_id])
    @bid = @auction.bids.find(params[:id])
    if current_user == @bid.user && @bid.destroy 
      if @auction.bids.present?
        @auction.update_attributes(current_price: @auction.bids.first.price + 1)
        else
        @auction.update_attributes(current_price: 0)
        end
      redirect_to @auction, alert: "Bid deleted!"
    else
      flash.now[:alert] = "Delete failed"
      render "auctions/show"  
    end
  end
  
  private
    def valid_bid 
       @bid.price.present? && current_user != @auction.user && @bid.price > @auction.current_price && @bid.save  
    end
    def bids_params
      params.require(:bid).permit([:price])
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def index
    @users = User.all
  end
  def show
    @user = User.find(params[:id])
    @bids = @user.bids.paginate(:page => params[:page], :per_page => 10)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
   @auctions = Auction.published.paginate(:page => params[:page], :per_page => 3).order("created_at DESC")
   # @auctions = Auction.published.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_messages 
    f = " "
    flash.each do |t,v|
      f += content_tag(:div, v, class: flash_class(t.to_sym))
    end
    content_tag(:div, f.html_safe)
  end
  def flash_class(type)
    case type
      when :notice then "alert altert-info"
      when :success then "alert alert-success"
      when :alert then "alert alert-danger"
    end
  end
end

app/helpers/auctions_helper.rb
module AuctionsHelper
  def state_label(state)
    case state.to_sym
    when :draft then "label label-default"
    when :published then "label label-info"
    when :reserve_met then "label label-primary"
    end
  end
end

app/helpers/bids_helper.rb
module BidsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/auctions/_form.html.haml
= form_for @auction do |f|
  .form-field 
    = f.label :title 
    = f.text_field :title, class: 'form-control' 
  .form-field
    = f.label :details 
    = f.text_field :details, class: 'form-control' 
  .form-field
    = f.label :ends_on 
    %br
    %p
    = f.datetime_select :ends_on, class: 'form-control' 
    %br
    %br
  .form-field
    = f.label :reserve_price
    = f.number_field :reserve_price, class: 'form-control' 
  = f.submit (@auction.persisted? ? "Update" : "Save"), class: "btn btn-default"

app/views/auctions/edit.html.erb
<h1> Editing Auction with the Id <%= @auction.id %> </h1>

<%= render 'form' %>

app/views/auctions/index.html.erb
<h1> Listing My Auctions </h1>
<%= link_to "Create a new Auc", new_auction_path, class: "btn btn-primary" %>
<br>
<br>
<%= will_paginate @auctions, renderer: BootstrapPagination::Rails %>

<% if @auctions.empty? %>
  <h2> you have made no auctions <h2>
<% end %>      
<% @auctions.each do |a| %>
  <div class= "well">
    <h2> <%= link_to a.title, auction_path(a) %></h2>
    <div class="pull-right">
    <% if a.draft? %>
      <%= button_to "Publish!", publish_auction_path(a), class: "btn btn-info", method: :patch %>
    <% end %>
      <label class="<%= state_label(a.state) %>"> <%= a.state.capitalize %>
      </label>
    </div>
    <%= a.details %>
    <p> Posted by: <%= a.user.user_name %> </p>
    <p> Created <%= time_ago_in_words(a.created_at) %> ago</p>
  </div>
<% end %>

app/views/auctions/new.html.erb
<h1> New Auction page </h1>
<% if @auction.errors.any? %>
  <ul> <% @auction.errors.full_messages.each do |m| %>
    <li><%= m %></li>
  <% end %></ul>
<% end %>

<%= render 'form' %>

app/views/auctions/show.html.erb
<h1> Auction  Show Page </h1>
  <div class="pull-right">
      <% if @auction.bids.present? && @auction.bids.first.user == current_user && (@auction.bids.first.price + 1) >= @auction.reserve_price %>
      <%= button_to "You can now reserve this item!", reserve_auction_path(@auction), class: "btn btn-default", method: :patch %>
      <% elsif @auction.reserve_met? %>
        <h3> Item has been reserved </h3>
      <% else  %>      
        <h3> Reserve not met </h3>
      <% end %>  
  </div>  
<h1> <%= @auction.title %></h1>
<p> Item Deets: <%= @auction.details %>
<p> Ends in: <%= time_ago_in_words(@auction.ends_on) if @auction.ends_on.present?  %>
<p> Reserve price: <%= @auction.reserve_price %>
<p> Current bid <span class="current_price"><%= @auction.current_price %></span>
<p> Posted: <%= time_ago_in_words(@auction.created_at) %> ago
<% if current_user == @auction.user %>
  <%= link_to "Edit", edit_auction_path(@auction) %>
  |
  <%= link_to "Delete", @auction, method: :delete, data: {confirm: "U sure"} %>
<% end %>
<br>
<div class= "well" >
<% if @bid.errors.any? %>
  <h2> <%= @bid.errors.messages %> </h2>
<% end %>

<h2> 
    <%= form_for [@auction, @bid], html: { class: "form-horizontal" }, remote: true  do |f| %>

  <div class="form-field">
      <%= f.label :price, "Place your bid" %>
      <%= f.number_field :price, class: "form-control" %>
  </div>
  <br>
  <%= f.submit "bid", class: "btn btn-default" %>

<% end %>
</div>
<h3> All bids </h3>
<ul class="list-group" id= "bid_list" >
  <% @bids.each do |bid| %>
    <%= render "/bids/bid", bid: bid %>
  <% end %>
  <%= will_paginate @bids, renderer: BootstrapPagination::Rails %>
</ul>

app/views/bids/_bid.html.erb
<li class= "list-group-item", id= "<%= dom_id(bid) %>" > 
  <%= bid.price %> 
  <% if bid.user == current_user %>  
    <div class= "pull-right">
      <%= button_to "x", [@auction, bid] , method: :delete, class: "btn btn-danger" %>
    </div>
  <% end %>
    <p> posted by: <%= bid.user.user_name %> 
</li>

app/views/bids/create.js.haml
$('#bid_price').val(""); 
$('#bid_list').prepend("#{j render 'bid', bid: @bid}");
$("##{dom_id(@bid)}").hide().fadeIn(500);
$(".current_price").html("#{@bid.auction.current_price}");
if ("#{@auction.bids.present? && @auction.bids.first.user == current_user && (@auction.bids.first.price + 1) >= @auction.reserve_price}") { $('h3').first().html("#{ 'Reserve button appears upon refresh if your bid is eligible'  }") }

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FinalExam1</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class= "container">
  <nav class= "nav-main">
  <%= link_to "Published Auctions", root_path, class: "btn btn-primary" %> 
  <%= link_to "My Auctions", auctions_path, class: "btn btn-primary" %>  <%= link_to "New Auction", new_auction_path, class: "btn btn-primary" %> 
  <%= link_to "All Users", profiles_path, class: "btn btn-primary" %> 

  
  <% if user_signed_in? %>
   <div class="pull-right"> 
    <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "btn btn-danger" %>  
     Hola <%= current_user.user_name %>
      </div>
  <% else %>
     <div class="pull-right"> 
       <%= button_to "Sign in", new_user_session_path, class: "btn btn-primary" %> 
     </div>
    <%= link_to "Sign Up NOW", new_user_registration_path, class: "btn btn-warning" %> 
  <% end %>
  
  </nav>
  
    
  <br>
  <%= flash_messages %>
  
  <%= yield %>
  </div>
</body>
</html>

app/views/profiles/index.html.erb
<h1> User Index </h1>
<% if @users.empty? %>
  <h2> This a Lonely app, no users available <h2>
<% end %>      
<% @users.each do |a| %>
  <div class= "well">
    <h4> User name: <%= link_to a.user_name, profile_path(a) %></h4>
  </div> 
<% end %>

app/views/profiles/show.html.erb
<h1> User and bids collide! </h1>
<h2> Profile for <%= @user.user_name %></h1>
<h2> The Bid Index </h1>
<% if @bids.empty? %>
  <h2> This is a cheap guy, no bids available <h2>
<% end %>      
<%= will_paginate @bids, renderer: BootstrapPagination::Rails %>
<% @bids.each do |a| %>
  <div class= "well">
    <h4> Bid: $ <%= a.price %>
    <% if a.auction.present? %> 
    for auction: <%= a.auction.title %></h4>
    <% end %>
  </div>
<% end %>

app/views/welcome/index.html.erb
<h1> Listing all Published Auctions </h1>
<%= link_to "Create a new Auc", new_auction_path, class: "btn btn-primary" %>
<br>
<%= will_paginate @auctions, renderer: BootstrapPagination::Rails %>
<br>
<% if @auctions.empty? %>
<div class= "well">
  <h2> There are no auctions available at this time <h2>
</div>
<% end %>      

<% @auctions.each do |a| %>
<div class="well">
  <div class="pull-right">
    <label class="<%= state_label(a.state) %>"> <%= a.state.capitalize %>
    </label>
  </div>
  <h2> <%= link_to a.title, auction_path(a) %></h2>
  <%= a.details %>
  <p> Posted by: <%= a.user.user_name %> </p>
  <p> Created <%= time_ago_in_words(a.created_at) %> ago</p>
</div>
<br>
<% end %>
  
  